### ISSUE TITLE
java.security.InvalidKeyException: Unsupported key size

### ISSUE THREAD

**Issue by RozinaDarediya** [Sameer-Jani-201/PayTMDemo#1]
@Sameer-Jani-201 
I  am getting the error at following line:
 checkSum = CheckSumServiceHelper.getCheckSumServiceHelper().genrateCheckSum("Merchant_Private_Key", paramMap);

plz reply as soon as possible

**Comment by Sameer-Jani-201** [comment]
Hello @RozinaDarediya ,
It's working fine here.
We need merchant private key to pass here.
Have you registered using https://business.paytm.com?
If yes then you will get merchant ID & merchant key,
So, above code inside need to pass Merchant Key,
And inside t params, we need to pass merchant ID. transaction amount.Unique custom orderID,Unique customer id,INDUSTRY_TYPE_ID as Retail,Channel ID as WAP,Website for demo please use APP_STAGING,Theme merchant,and last checksum from above generated code.

Although, If you are facing any issue please tell me..
Thanks for use.

**Comment by RozinaDarediya** [comment]
Hello @Sameer-Jani-201 , 
Yes I am able to figure out the solution. 
Thank you.
